version: '3.7'
services:
  app-node:
    image: springbootdynamodb:latest
    container_name: app-node
    ports:
      - "8500:8500"
    depends_on:
      - "dynamodb-local"
    links:
      - "dynamodb-local"
    environment:
      - AWS_ACCESS_KEY_ID='DUMMYIDEXAMPLE'
      - AWS_SECRET_ACCESS_KEY='DUMMYEXAMPLEKEY'
      - REGION='eu-east-1'
      - amazon.dynamodb.endpoint=http://dynamodb-local:8000

    networks:
      - my-network
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    volumes:
      - dynamodata:/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
    networks:
      - my-network
volumes:
  dynamodata:

networks:
  my-network:
    driver: bridge