package com.spring.token.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.xspec.NULL;

import java.util.Date;

/**
 * Created by prkumar on 08/10/2020.
 */
@DynamoDBTable(tableName = "token")
public class Token {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute(attributeName = "Access_token")
    private String accessToken;
    @DynamoDBAttribute(attributeName = "App_id")
    private String appId;
    @DynamoDBAttribute(attributeName = "Date_inserted")
    private Date dateInserted;
    @DynamoDBAttribute(attributeName = "Date_created")
    private Date dateCreated;
    @DynamoDBAttribute(attributeName = "Date_expiry")
    private Date dateExpiry;
    @DynamoDBAttribute(attributeName = "Login_user_id")
    private int loginUserId;
    @DynamoDBAttribute(attributeName = "Client_Account_id")
    private int clientAccountId;
    @DynamoDBAttribute(attributeName = "Date_moved")
    private Date dateMoved;
    @DynamoDBAttribute(attributeName = "Status")
    private int status;
    @DynamoDBAttribute(attributeName = "type")
    private String type;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getAccessToken() {
        return accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    public String getAppId() {
        return appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    public Date getDateInserted() {
        return dateInserted;
    }

    public void setDateInserted(Date dateInserted) {
        this.dateInserted = dateInserted;
    }

    public Date getDateCreated() {
        return dateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    public Date getDateExpiry() {
        return dateExpiry;
    }

    public void setDateExpiry(Date dateExpiry) {
        this.dateExpiry = dateExpiry;
    }

    public int getLoginUserId() {
        return loginUserId;
    }

    public void setLoginUserId(int loginUserId) {
        this.loginUserId = loginUserId;
    }

    public int getClientAccountId() {
        return clientAccountId;
    }

    public void setClientAccountId(int clientAccountId) {
        this.clientAccountId = clientAccountId;
    }

    public Date getDateMoved() {
        return dateMoved;
    }

    public void setDateMoved(Date dateMoved) {
        this.dateMoved = dateMoved;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }


}
